#version: '3.11'

services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - database_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always

  weread-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev_build
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  database_data:
  static:
  media: